# Generated by Django 4.2.28 on 2026-02-26 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_add_category_and_event_fields'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='Base URL of the site, e.g. https://www.plymouthculture.co.uk')),
                ('api_path', models.CharField(blank=True, help_text='Path to the events API/page, e.g. /events-1', max_length=255)),
                ('scraper_task_name', models.CharField(help_text='Dotted path to the Celery task, e.g. scraping.tasks.scrape_plymouth_culture', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('scrape_interval_hours', models.PositiveIntegerField(default=24)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('events_found', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('events_updated', models.PositiveIntegerField(default=0)),
                ('events_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scraping.scrapesource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full JSON from the source API')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('venue_postcode', models.CharField(blank=True, max_length=10)),
                ('venue_lat', models.FloatField(blank=True, null=True)),
                ('venue_lng', models.FloatField(blank=True, null=True)),
                ('categories_raw', models.JSONField(blank=True, default=list)),
                ('tags_raw', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('auto_matched', 'Auto-Matched'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_event', models.ForeignKey(blank=True, help_text='Existing event this was matched to (for updates/dedup)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_matches', to='events.event')),
                ('matched_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_matches', to='organisations.location')),
                ('matched_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_matches', to='organisations.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_imports', to=settings.AUTH_USER_MODEL)),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_events', to='scraping.scraperun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_events', to='scraping.scrapesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='importedevent',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id'),
        ),
    ]
