# Generated by Django 4.2.16 on 2026-02-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHashInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(db_index=True, max_length=64)),
                ('interaction_type', models.CharField(choices=[('event', 'Event'), ('location', 'Location')], max_length=20)),
                ('interaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='events.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='organisations.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-interaction_date'],
                'indexes': [models.Index(fields=['user_hash', 'interaction_date'], name='analytics_u_user_ha_e64d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostcodeAreaInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=10)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcode_interactions', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-period_end', '-interaction_count'],
                'indexes': [models.Index(fields=['postcode', 'period_start', 'period_end'], name='analytics_p_postcod_15e659_idx')],
            },
        ),
    ]
