# Generated by Django 4.2.28 on 2026-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending geocoding'), ('success', 'Successfully geocoded'), ('failed', 'Geocoding failed (will not retry)')], db_index=True, default='pending', max_length=20)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['postcode'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='analytics_p_status_328f82_idx')],
            },
        ),
    ]
