# Generated by Django 4.2.28 on 2026-07-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_search_and_embeddings'),
        ('organisations', '0005_location_parent'),
        ('analytics', '0002_add_postcode_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeEventInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=10)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('interaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcode_interactions', to='events.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcode_event_interactions', to='organisations.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcode_event_interactions', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-interaction_date', '-interaction_count'],
                'indexes': [models.Index(fields=['postcode', 'interaction_date'], name='analytics_p_postcod_c192da_idx')],
            },
        ),
    ]
