# Generated by Django 4.2.28 on 2026-07-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_location_parent'),
        ('events', '0003_search_and_embeddings'),
        ('analytics', '0003_postcodeeventinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeTicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=10)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('ticket_quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcode_ticket_purchases', to='events.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcode_ticket_purchases', to='organisations.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcode_ticket_purchases', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['postcode', 'purchase_date'], name='analytics_p_postcod_5ec8be_idx')],
            },
        ),
    ]
