# Generated by Django 4.2.28 on 2026-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_postcodeticketpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('precipitation_mm', models.FloatField(blank=True, null=True)),
                ('weather_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
