# Generated by Django 4.2.28 on 2026-09-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_location_parent'),
        ('analytics', '0006_dailyweather_wind_sunshine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='userhashinteraction',
            index=models.Index(fields=['organisation', 'interaction_date'], name='analytics_u_organis_9cf724_idx'),
        ),
        migrations.AddField(
            model_name='dailystatssnapshot',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats_snapshots', to='organisations.organisation'),
        ),
        migrations.AddIndex(
            model_name='dailystatssnapshot',
            index=models.Index(fields=['organisation', 'date'], name='analytics_d_organis_118ec8_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystatssnapshot',
            constraint=models.UniqueConstraint(fields=('date', 'organisation'), name='unique_daily_stats_snapshot_per_org'),
        ),
    ]
