# Generated by Django 4.2.28 on 2026-09-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_orggoal'),
        ('analytics', '0007_dailystatssnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('off', 'Off'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='off', max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_subscription', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=20)),
                ('week_start', models.DateField()),
                ('actual_value', models.FloatField()),
                ('baseline_mean', models.FloatField()),
                ('baseline_stddev', models.FloatField()),
                ('z_score', models.FloatField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='anomalyalert',
            constraint=models.UniqueConstraint(fields=('organisation', 'metric', 'week_start'), name='unique_anomaly_alert'),
        ),
    ]
