# Generated by Django 4.2.28 on 2026-05-07 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(help_text="SPA route, e.g. '/app/map3d' or '/app/postcodes3d'.", max_length=255)),
                ('query_string', models.TextField(blank=True, help_text="URL-encoded filter querystring, no leading '?'.")),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_savedview_user_name'),
        ),
    ]
