"""
Enrich Event records created by import_partner_csv with descriptions,
categories, end datetimes, and start times derived from the synthesised
events catalogue (csv_exports/synthesised_events.csv).

The catalogue is generated by scripts/synthesise_events.py from the
partner booking CSVs. This command is idempotent: it updates existing
Event records that match on (org, title, event_date) and creates new ones
for any rows that don't yet have a matching Event.

Usage:
    python manage.py enrich_events
    python manage.py enrich_events --path path/to/synthesised_events.csv
    python manage.py enrich_events --dry-run
"""

from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.utils import timezone

from events.models import Category, Event
from organisations.models import Organisation


class Command(BaseCommand):
    help = "Enrich Event records from the synthesised events catalogue CSV."

    def add_arguments(self, parser):
        parser.add_argument(
            "--path",
            type=str,
            default=None,
            help="Path to synthesised_events.csv (default: csv_exports/synthesised_events.csv).",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and report only — no database writes.",
        )

    def handle(self, *args, **options):
        csv_path = Path(options["path"]) if options["path"] else settings.BASE_DIR / "csv_exports" / "synthesised_events.csv"
        dry_run = options["dry_run"]

        if not csv_path.exists():
            self.stderr.write(self.style.ERROR(
                f"Synthesised events catalogue not found: {csv_path}\n"
                "Run: python scripts/synthesise_events.py"
            ))
            return

        # Pre-load org and category caches
        org_cache: dict[str, Organisation | None] = {}
        cat_cache: dict[str, Category] = {}

        created = updated = skipped = 0

        with csv_path.open(newline="", encoding="utf-8-sig") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                org_name = (row.get("org_name") or "").strip()
                title = (row.get("event_title") or "").strip()
                date_str = (row.get("event_date") or "").strip()
                time_str = (row.get("event_time") or "").strip()
                end_time_str = (row.get("end_time") or "").strip()
                category_name = (row.get("category") or "").strip()
                description = (row.get("description") or "").strip()
                url = (row.get("url") or "").strip()

                if not (org_name and title and date_str):
                    skipped += 1
                    continue

                # Parse start datetime
                try:
                    naive_dt = datetime.strptime(
                        f"{date_str} {time_str or '18:00'}",
                        "%Y-%m-%d %H:%M",
                    )
                except ValueError:
                    skipped += 1
                    continue
                start_dt = timezone.make_aware(naive_dt)

                # Parse end datetime
                end_dt = None
                if end_time_str:
                    try:
                        naive_end = datetime.strptime(
                            f"{date_str} {end_time_str}",
                            "%Y-%m-%d %H:%M",
                        )
                        end_dt = timezone.make_aware(naive_end)
                        # Handle events that cross midnight
                        if end_dt <= start_dt:
                            from datetime import timedelta
                            end_dt += timedelta(days=1)
                    except ValueError:
                        end_dt = None

                # Resolve org (cache miss → DB lookup)
                if org_name not in org_cache:
                    try:
                        org_cache[org_name] = Organisation.objects.get(name=org_name)
                    except Organisation.DoesNotExist:
                        org_cache[org_name] = None
                org = org_cache[org_name]
                if org is None:
                    skipped += 1
                    continue

                # Resolve or create category
                if category_name and category_name not in cat_cache:
                    cat, _ = Category.objects.get_or_create(name=category_name)
                    cat_cache[category_name] = cat
                category = cat_cache.get(category_name)

                # Find matching Event: same org + title + same calendar date
                # (we match on date only, not exact time, because import_partner_csv
                # stores the time from the booking CSV which may differ from our
                # synthesised time)
                event_qs = Event.objects.filter(
                    organisation=org,
                    title=title,
                    start_datetime__date=start_dt.date(),
                )

                if dry_run:
                    if event_qs.exists():
                        self.stdout.write(f"  [DRY RUN] would update: {org.name} / {title} / {date_str}")
                        updated += 1
                    else:
                        self.stdout.write(f"  [DRY RUN] would create: {org.name} / {title} / {date_str}")
                        created += 1
                    continue

                if event_qs.exists():
                    # Update all matching events (there may be >1 if OCT had
                    # multiple bookings on the same date for the same title)
                    for event in event_qs:
                        fields_changed = []

                        if description and not event.description:
                            event.description = description
                            fields_changed.append("description")

                        if end_dt and not event.end_datetime:
                            event.end_datetime = end_dt
                            fields_changed.append("end_datetime")

                        if url and not event.url:
                            event.url = url
                            fields_changed.append("url")

                        if fields_changed:
                            event.save(update_fields=fields_changed)
                            updated += 1
                        else:
                            # Already enriched; just make sure category is linked
                            pass

                        if category:
                            event.categories.add(category)

                else:
                    # Create the event
                    location = org.locations.first()
                    event = Event.objects.create(
                        organisation=org,
                        title=title,
                        description=description,
                        start_datetime=start_dt,
                        end_datetime=end_dt,
                        location=location,
                        url=url or "",
                        source_tags=[category_name.lower()] if category_name else [],
                    )
                    if category:
                        event.categories.add(category)
                    created += 1

        summary = (
            f"enrich_events complete — "
            f"created: {created}, updated: {updated}, skipped: {skipped}"
        )
        if dry_run:
            summary = "[DRY RUN] " + summary
        self.stdout.write(self.style.SUCCESS(summary))
