# Generated by Django 4.2.16 on 2026-02-26 15:20

import django.db.models.deletion
from django.db import migrations, models

try:
    import django.contrib.gis.db.models.fields
    _POINT_FIELD = django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)
    _USE_GIS = True
except Exception:
    _USE_GIS = False


def _location_point_field():
    if _USE_GIS:
        return ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326))
    return ('point', models.CharField(blank=True, max_length=100))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=10)),
                _location_point_field(),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
