# Generated by Django 4.2.28 on 2026-05-07 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0003_search_and_embeddings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-is_partner', 'name']},
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_partner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organisations.organisation'),
        ),
    ]
