# Generated by Django 4.2.28 on 2026-09-07 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0005_location_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('events', 'Events'), ('interactions', 'Interactions'), ('unique_visitors', 'Unique visitors')], max_length=20)),
                ('target_value', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['organisation', 'period_start', 'period_end'], name='organisatio_organis_824319_idx')],
            },
        ),
    ]
